const db = require('./config/db');

const pets = [
    {
        name: 'Bruno',
        type: 'Dog',
        breed: 'Labrador Mix',
        age: '2 years',
        gender: 'Male',
        size: 'Large',
        energy_level: 'active',
        temperament: ['Friendly', 'Playful', 'Smart'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: false, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356657/pawmatch/static/dcvu0cfgqnbxk9y3g8gv.jpg',
        description: 'Bruno is a high-energy lab mix who loves to play fetch and swim. He is looking for an active family.',
        is_foster: false,
        weight: '28kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Luna',
        type: 'Dog',
        breed: 'Beagle',
        age: '4 years',
        gender: 'Female',
        size: 'Medium',
        energy_level: 'moderate',
        temperament: ['Gentle', 'Curious', 'Food-motivated'],
        social_profile: { dogs: true, cats: false, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356661/pawmatch/static/i8x0yr1fhvdnsp0ssk4b.jpg',
        description: 'Luna is a sweet beagle who loves sniffaris and following her nose. She gets along well with children.',
        is_foster: false,
        weight: '12kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'German Shepherd',
        age: '3 years',
        gender: 'Male',
        size: 'Large',
        energy_level: 'athletic',
        temperament: ['Loyal', 'Protective', 'Intelligent'],
        social_profile: { dogs: false, cats: false, kids: false },
        living_situation_match: { apartment: false, house_small: false, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356665/pawmatch/static/ezt1gzszgkja8kuviaez.jpg',
        description: 'Rocky is a highly intelligent and loyal protector. He needs an experienced owner and plenty of space to run.',
        is_foster: false,
        weight: '35kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Mochi',
        type: 'Dog',
        breed: 'Pomeranian',
        age: '1 year',
        gender: 'Female',
        size: 'Small',
        energy_level: 'moderate',
        temperament: ['Playful', 'Spirited', 'Affectionate'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356682/pawmatch/static/skc5yxnwkn5zgxzw8uwy.jpg',
        description: 'Mochi is a tiny cloud of joy. She loves attention and curling up on a cozy lap.',
        is_foster: true,
        weight: '3kg',
        is_vaccinated: true,
        is_neutered: false,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Oliver',
        type: 'Dog',
        breed: 'Border Collie Mix',
        age: '1.5 years',
        gender: 'Male',
        size: 'Medium',
        energy_level: 'athletic',
        temperament: ['Focused', 'Energetic', 'Work-oriented'],
        social_profile: { dogs: true, cats: false, kids: true },
        living_situation_match: { apartment: false, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356666/pawmatch/static/ztexpfcox3zagdsacg7f.jpg',
        description: 'Oliver is a smart boy who needs mental stimulation. He loves learning new tricks and agility training.',
        is_foster: false,
        weight: '18kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Daisy',
        type: 'Dog',
        breed: 'Mixed Breed',
        age: '6 years',
        gender: 'Female',
        size: 'Medium',
        energy_level: 'sedentary',
        temperament: ['Calm', 'Gentle', 'Soulful'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356659/pawmatch/static/ouw2ednuhsqd0l1txfly.jpg',
        description: 'Daisy is a mature lady who appreciates the finer things in life: a soft bed and a gentle ear scratch.',
        is_foster: false,
        weight: '15kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Shadow',
        type: 'Dog',
        breed: 'Street Dog Mix',
        age: '2.5 years',
        gender: 'Male',
        size: 'Medium',
        energy_level: 'active',
        temperament: ['Resilient', 'Observant', 'Loyal'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356662/pawmatch/static/f2knlxfmyo5mzhqaz3lp.jpg',
        description: 'Shadow is a survivor who has found his heart. He is incredibly loyal to those he trusts.',
        is_foster: false,
        weight: '14kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: false,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Honey',
        type: 'Dog',
        breed: 'Golden Mixed',
        age: '8 months',
        gender: 'Female',
        size: 'Medium',
        energy_level: 'active',
        temperament: ['Bubbly', 'Friendly', 'Clumsy'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356664/pawmatch/static/zc6enktpeo4fvn6n4evj.jpg',
        description: 'Honey is as sweet as her name. She is still learning her manners but has a heart of gold.',
        is_foster: true,
        weight: '16kg',
        is_vaccinated: true,
        is_neutered: false,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Whiskers',
        type: 'Cat',
        breed: 'Domestic Shorthair',
        age: '2 years',
        gender: 'Male',
        size: 'Small',
        energy_level: 'low',
        temperament: ['Quiet', 'Independent', 'Cuddly'],
        social_profile: { dogs: false, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80',
        description: 'Whiskers is a professional napper. He loves sleeping in sunbeams and chasing the occasional laser pointer.',
        is_foster: false,
        weight: '4.5kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Cleo',
        type: 'Cat',
        breed: 'Siamese Mix',
        age: '5 years',
        gender: 'Female',
        size: 'Small',
        energy_level: 'moderate',
        temperament: ['Talkative', 'Elegant', 'Attached'],
        social_profile: { dogs: true, cats: true, kids: false },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: false },
        image_url: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80',
        description: 'Cleo is a sophisticated lady who will tell you all about her day. She needs a calm environment.',
        is_foster: false,
        weight: '3.8kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Simba',
        type: 'Cat',
        breed: 'Ginger Tabby',
        age: '4 months',
        gender: 'Male',
        size: 'Small',
        energy_level: 'active',
        temperament: ['Adventurous', 'Playful', 'Fearless'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://images.unsplash.com/photo-1574158622642-43958066c1b3?auto=format&fit=crop&q=80',
        description: 'Simba is a tiny lion heart. He loves climbing and exploring every nook and cranny of his home.',
        is_foster: true,
        weight: '1.2kg',
        is_vaccinated: false,
        is_neutered: false,
        is_microchipped: false,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Toby',
        type: 'Dog',
        breed: 'Local Breed',
        age: '5 years',
        gender: 'Male',
        size: 'Medium',
        energy_level: 'moderate',
        temperament: ['Grateful', 'Watchful', 'Steady'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356660/pawmatch/static/toptiuvojrqheyoiugio.jpg',
        description: 'Toby was a community favorite who is now looking for a family to call his own. He is very well-behaved.',
        is_foster: false,
        weight: '16kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Baggie',
        type: 'Cat',
        breed: 'Black Cat',
        age: '1 year',
        gender: 'Female',
        size: 'Small',
        energy_level: 'active',
        temperament: ['Sleek', 'Mysterious', 'Vibrant'],
        social_profile: { dogs: false, cats: false, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80',
        description: 'Baggie is a sleek black cat who loves high places and surveying her kingdom.',
        is_foster: false,
        weight: '4kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Ginger',
        type: 'Dog',
        breed: 'Labrador',
        age: '6 months',
        gender: 'Female',
        size: 'Large',
        energy_level: 'active',
        temperament: ['Excitable', 'Loving', 'Hungry'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: false, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356668/pawmatch/static/zhnltumpyqssrmq3ofka.jpg',
        description: 'Ginger is a classic yellow lab puppy. She is eager to please and even more eager for treats.',
        is_foster: true,
        weight: '14kg',
        is_vaccinated: true,
        is_neutered: false,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Pepper',
        type: 'Cat',
        breed: 'Longhair Mix',
        age: '3 years',
        gender: 'Female',
        size: 'Medium',
        energy_level: 'low',
        temperament: ['Soft', 'Mellow', 'Shy'],
        social_profile: { dogs: true, cats: true, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?auto=format&fit=crop&q=80',
        description: 'Pepper is a fluffy beauty who needs regular brushing and lots of love.',
        is_foster: false,
        weight: '5kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    },
    {
        name: 'Sparky',
        type: 'Dog',
        breed: 'Jack Russell Mix',
        age: '2 years',
        gender: 'Male',
        size: 'Small',
        energy_level: 'athletic',
        temperament: ['Tenacious', 'Spunky', 'Loyal'],
        social_profile: { dogs: true, cats: false, kids: true },
        living_situation_match: { apartment: true, house_small: true, house_large: true, rural: true },
        image_url: 'https://res.cloudinary.com/dd58qgsfx/image/upload/v1770356681/pawmatch/static/o5qc2jpoqjiet0bq9i7a.jpg',
        description: 'Sparky has energy for days. He loves playing ball and would make a great running partner.',
        is_foster: false,
        weight: '7kg',
        is_vaccinated: true,
        is_neutered: true,
        is_microchipped: true,
        is_health_checked: true,
        status: 'available'
    }
];

async function seed() {
    try {
        console.log('Cleaning existing data (disabling FK checks)...');
        await db.query('SET FOREIGN_KEY_CHECKS = 0');

        await db.query('DELETE FROM welfare_logs');
        await db.query('DELETE FROM adoptions');
        await db.query('DELETE FROM shelter_messages');
        await db.query('DELETE FROM shelter_visits');
        await db.query('DELETE FROM pets');

        await db.query('ALTER TABLE pets AUTO_INCREMENT = 1');
        await db.query('ALTER TABLE adoptions AUTO_INCREMENT = 1');
        await db.query('ALTER TABLE welfare_logs AUTO_INCREMENT = 1');
        await db.query('ALTER TABLE shelter_visits AUTO_INCREMENT = 1');

        console.log('Seeding new pets with varied data...');
        for (const pet of pets) {
            await db.query(
                `INSERT INTO pets (
                    name, type, breed, age, gender, size, energy_level, 
                    temperament, social_profile, living_situation_match, 
                    image_url, description, is_foster, weight, 
                    is_vaccinated, is_neutered, is_microchipped, is_health_checked, status
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
                [
                    pet.name, pet.type, pet.breed, pet.age, pet.gender, pet.size, pet.energy_level,
                    JSON.stringify(pet.temperament), JSON.stringify(pet.social_profile),
                    JSON.stringify(pet.living_situation_match),
                    pet.image_url, pet.description, pet.is_foster, pet.weight,
                    pet.is_vaccinated, pet.is_neutered, pet.is_microchipped, pet.is_health_checked, pet.status
                ]
            );
        }

        await db.query('SET FOREIGN_KEY_CHECKS = 1');
        console.log(`Successfully seeded ${pets.length} pets with high-quality data.`);
        process.exit(0);
    } catch (error) {
        await db.query('SET FOREIGN_KEY_CHECKS = 1');
        console.error('Seeding error:', error);
        process.exit(1);
    }
}

seed();
